---
name: Build with Podman

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}
env:
  REGISTRY: quay.io
  IMAGE_NAME: nikolasheva/my-bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Verify Podman installation
        run: podman --version

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login ${{ env.REGISTRY }} -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          podman build --pull-always \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v2 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -f Containerfile .

      - name: Push image
        run: |
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v2
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Get image digest
        id: image-digest
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v2"
          DIGEST=$(podman inspect --format '{{.Digest}}' "$IMAGE_TAG")
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Output digest
        run: |
          echo "Image digest: ${{ steps.image-digest.outputs.digest }}"
